server:
  port: 8081

spring:
  application:
    name: employee-service
    url: jdbc:mysql://localhost:3306/employeedb
    username: root
    password: user
  
  datasource:
    url: jdbc:mysql://localhost:3306/employeedb?useSSL=false&serverTimezone=UTC
    username: root
    password: user
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate.format_sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example.employee_service: DEBUG